spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://luckdb-dev.c12e70dbueew.ap-northeast-2.rds.amazonaws.com:3306/lck?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: luck
    password: rootluck123!
    ##  username: ENC(cN0s/mR5UggvjHYgMFI3rQ==)
    ##  password: ENC(+TXnxk0d55R4/NuLYoz0AnM3/A2hh4Nn)
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl.auto: none
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    principal-session:
      host: 127.0.0.1
      port: 26388
      connect-timeout: 3000
    redis-cache:
      host: 127.0.0.1
      port: 26388
      connect-timeout: 3000
    principal-migration-status:
      host: 127.0.0.1
      port: 26388

# 로그 설정
jasypt:
  encryptor:
    bean: jasyptEncryptor
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org:
      hibernate:
        sql: trace
        type: trace
### h2 세팅
##spring:
##  h2:
##    console:
##      enabled: true
##      path: /h2-console
##  datasource:
##    url: jdbc:h2:~/test;MODE=mysql;
##    username: test
##    password:
##    driver-class-name: org.h2.Driver
##
##  jpa:
##    properties:
##      hibernate:
##        format_sql: true
##        show_sql: true
##    hibernate:
##      ddl-auto: create
##    database-platform: org.hibernate.dialect.H2Dialect
##    generate-ddl: true
#

###jwt 설정
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

s3:
  img:
    url: https://pureluckupload.s3.ap-northeast-2.amazonaws.com
    full:
      url: https://pureluckupload.s3.ap-northeast-2.amazonaws.com/img


